### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by Bananaman** [pingzing/LittleBuster#18]
Thanks for reviving the RatingBuster idea and for creating a brilliant, modern rewrite! It's beautiful! :)

**Comment by Bananaman** [comment]
Oh and by the way, I've just noticed that https://www.curseforge.com/wow/addons/little-buster/files (July 5th) is outdated compared to this repo's July 7th fixes. And the repo itself needs tags for newer versions. ;)

**Comment by pingzing** [comment]
You're welcome!

The fixes in the repo will be rolled into 1.12.0. That'll include either Stamina or Strength, plus all the little QoL fixes that have gone in since the July 5th release.

Repo releases updated. They're manually-updated, and I tend to slack a little on those, because I know GitHub's not really where the primary audience for this addon is.

**Comment by Bananaman** [comment]
@pingzing Thanks, I have been using the addon for a day now and I am *super impressed*. It's brilliant. :)

**Comment by Bananaman** [comment]
@pingzing I see 1.12.1 released today, and added stamina support. Very useful as a tank. Thanks a lot! :)
